INSERT INTO GENRE (ID, NAME) VALUES (1, 'Novel');
INSERT INTO GENRE (ID, NAME) VALUES (2, 'Mystery');
INSERT INTO GENRE (ID, NAME) VALUES (3, 'Fantasy');
INSERT INTO GENRE (ID, NAME) VALUES (4, 'Drama');
INSERT INTO GENRE (ID, NAME) VALUES (5, 'Criminal');
INSERT INTO GENRE (ID, NAME) VALUES (6, 'Comedy');
INSERT INTO GENRE (ID, NAME) VALUES (7, 'SF');